# Generated by Django 3.1 on 2020-11-24 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20201124_1405'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-completed']},
        ),
    ]
